<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TravellerGenesis</AssemblyName>
    <RootNamespace>TravellerGenesis</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TravellerGenesis.Core\TravellerGenesis.Core.csproj" />
  </ItemGroup>

</Project>
